This is makeindex, version 2.15 [TeX Live 2013] (kpathsea + Thai support).
Scanning style file ./ComputerScienceOne.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file ComputerScienceOne.acn....done (55 entries accepted, 0 rejected).
Sorting entries....done (350 comparisons).
Generating output file ComputerScienceOne.acr....done (95 lines written, 0 warnings).
Output written in ComputerScienceOne.acr.
Transcript written in ComputerScienceOne.alg.
